name: Run deken
on: [push, pull_request]
jobs:
  deken-package:
    runs-on: ubuntu-latest
    steps:
      - name: Install deken
        run: |
          sudo apt-get install --no-install-recommends deken
      - name: Create a home for deken
        # See https://github.com/pure-data/deken/issues/247
        run: |
          mkdir ~/.deken
      - name: Run deken
        run: |
          deken -h
